[package]
name = "wallpaper_slideshow"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.42"
libc = "0.2.178"
rand = "0.9.2"
rayon = "1.11.0"
rexif = "0.7.5"
walkdir = "2.5.0"
rusqlite = { version = "0.32", features = ["bundled"] }
